# Generated by Django 4.2.16 on 2024-11-09 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_team_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with_teams',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to='notes.team'),
        ),
        migrations.AddField(
            model_name='note',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
