# Generated by Django 4.2.16 on 2024-11-12 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0006_alter_category_name_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='namespace',
            field=models.CharField(default='personal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user', 'namespace')},
        ),
    ]
