# Generated by Django 4.2.16 on 2024-11-12 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_alter_category_unique_together_category_namespace_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='category',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
